# NB: this is only used for local development
# see Dockerfile for deployed version

db:
  image: postgres
  # links:
  #   - dbdata
  # volumes_from:
  #   - dbdata
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres

# dbdata:
#   image: busybox
#   command: tail -f /dev/null
#   volumes:
#     - /var/lib/postgresql/data

django:
  build: .
  command: ./run.sh testserve
  volumes:
    # - .:app
    - /tmp/pip_download_cache:/root/.cache/pip
  ports:
    - "8000:8000"
    - "8800:8800"
  links:
    - db
  environment:
    ENV: local
    DEBUG: "True"
    DJANGO_SECRET_KEY: CHANGE_ME
    DJANGO_SETTINGS_MODULE: mtp_api.settings.docker
    DB_NAME: mtp_api
    DB_USERNAME: postgres
    DB_PASSWORD: postgres
    DB_HOST: db
    DB_PORT: 5432
